apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tmx6y3peh-java-springboot
  janus-idp.io/tekton: tmx6y3peh-java-springboot
  backstage.io/kubernetes-id: tmx6y3peh-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tmx6y3peh-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
